name: K6 Load Test

on:
  push:
    branches: [ "master" ]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 test
        run: k6 run k6/load-test.js
